# Generated by Django 2.2.13 on 2020-06-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_commit_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='commit_3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
