# Generated by Django 2.2.13 on 2020-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_commit_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="commit_4",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
