# Generated by Django 2.2.13 on 2020-06-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_commit8'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test_1',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
