# Generated by Django 2.2.13 on 2020-06-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_test_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tst3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
