# Generated by Django 2.2.13 on 2020-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200616_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cc11',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
